# Generated by Django 5.2.14 on 2026-06-13 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 8, 33, 17, 505710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 8, 33, 17, 498520, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 8, 33, 17, 505499, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 8, 33, 17, 506062, tzinfo=datetime.timezone.utc)),
        ),
    ]
