# Generated by Django 5.2.14 on 2026-06-13 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2django', '0002_alter_cart_created_at_alter_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2005, 1, 17, 0, 0)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2005, 1, 17, 0, 0)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2005, 1, 17, 0, 0)),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2005, 1, 17, 0, 0)),
        ),
    ]
