# Generated by Django 5.2.14 on 2026-06-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2django', '0003_alter_cart_created_at_alter_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
