# Generated by Django 5.2.14 on 2026-06-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2django', '0004_cart_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
